### ISSUE TITLE
getElement's type states that it returns a HTMLElement, but it can also return null.

### ISSUE THREAD

**Issue by skulptur** [mediamonks/muban#109] opened 2019-09-26 18:24 UTC
```typescript
const myElement = this.getElement('[data-non-existent]') // => null
```

I can see how it is convenient to assume that the element was found and move on with the code, but then when using that element it will inevitably fail and the error will not be immediately obvious. I suggest we at least use selectors that fail on the spot with a proper message, so we can easily find mistakes in the template.

**Comment by ThaNarie** [comment] 2019-09-26 19:13
This is a duplicate of https://github.com/mediamonks/muban-core/issues/2, feel free to discuss there, since `CoreComponent` is part of `muban-core` :)

**Closed by ThaNarie** 2019-09-26 19:13 UTC
