### ISSUE TITLE
Add a way to access the parent instance

### ISSUE THREAD

**Issue by larsvanbraam** [mediamonks/muban#37] opened 2018-02-22 09:34 UTC
Sometimes you would like to access the parent instance of a component, I currently fixed this by adding a `getParent()` method in the AbstractComponent that looks for the closest `[data-component]` element and returns the instance. 

```typescript
/**
 * @public
 * @method getParent
 * @description Retrieve the components parent instance
 * @returns {AbstractComponent}
 */
public getParent():AbstractComponent {
  const parentElement = <HTMLElement>this.element.parentElement.closest('[data-component]');
  return parentElement ? <AbstractComponent>getComponentForElement(parentElement) : null;
}
```
I'm not sure if this is the best way to do this though!

**Comment by ThaNarie** [comment] 2018-03-07 10:56
This will work properly, but is looking up the parent every time you acces sit. Ideally we would like to have some caching; by storing the result on first lookup, or by setting it after creation.

The downside of caching is that theoretically a node can be moved around in the DOM, and then some children and parents could be different. So in that case we would like to re-fetch the parent. This means that having it as method is more flexible, since you can add additional params.

Another option would be to detect if the DOM node was moved around, and automatically re-set the parent.

Needs some investigation.

**Comment by ThijsTyZ** [comment] 2018-11-27 18:07
Please do not add a reference to the parent. I think this will only lead to bad code. A component should have access to it's children, but not the other way around. Calling method directly on a parent is bad practice in my opinion.

The problem is that a component has no control about his parent. There is no way a component can know what the type if it's parent is, because it can be created by any component. 
This is not the case for children. A component create it's own children and has therefor control over them and knows what the type of the children is. Calling methods on the children is therefor save to do, because the parent can know the structure of the children.

If you want your component to communicate with the parent, you can dispatch a bubbling event on it's own element. A bubbling event will reach the element of the parent(s), so the parent can listen for these events on his own element.

**Comment by ThaNarie** [comment] 2019-06-09 12:43
Wondering if @pigeonfresh @ReneDrie @riccoarntz or @nossienl ever needed this. I agree with @ThijsTyZ that it's not very good practice, and providing it by default might encourage using it. So i'd rather leave it as is, and let someone write that code themselves if needed.

I'm thinking how this would work in React/Vue, and it's either dispatching events / calling callbacks up the chain, or using some kind of context. The first option is supported, having a context not.

Would be useful to know when we might need such thing in Muban projects to see if/how we would add this.
A context is bound to the display tree, so any parent would register a context by providing an object and a dom element to link it to, which will add a data-context attribute.
When consuming a context it needs to be retrieved, where the helper function would loop up the closest parent element that has the specific context provided, so it can read a value or call a function on it.

If this Context thing is something we want, I can add a PR for it.

**Comment by pigeonfresh** [comment] 2019-06-09 13:00
I can't remember if I needed it or avoided using it.

**Comment by skulptur** [comment] 2020-02-09 03:12
Context is useful in React to avoid prop-drilling mainly. That is not a problem in Muban. Also people tend to overuse context and ignore this: https://reactjs.org/docs/context.html#before-you-use-context.

**Comment by ThaNarie** [comment] 2020-02-09 16:58
Closing this, a parent ref isn't needed since it leads to bad coding, and there are better ways to go about this.

**Closed by ThaNarie** 2020-02-09 16:58 UTC
Labels: enhancement, muban-core, needs research
